ALTER TYPE "ClientStageStatus" ADD VALUE IF NOT EXISTS 'BLOCKED';

ALTER TABLE "Stage" ADD COLUMN IF NOT EXISTS "parallelGroup" TEXT;
ALTER TABLE "ClientStage" ADD COLUMN IF NOT EXISTS "delayReason" TEXT;
ALTER TABLE "TaskTemplate" ADD COLUMN IF NOT EXISTS "estimatedDurationDays" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "TaskTemplate" ADD COLUMN IF NOT EXISTS "blocksPhaseCompletion" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "estimatedDurationDays" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "blocksPhaseCompletion" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "cycle" INTEGER;
